<?php
/**
 * Custom module for Changing Site Information Form.
 */

/**
 * Implements hook_form_alter()
 */
function siteinformationform_form_system_site_information_settings_alter(&$form, &$form_state, $form_id) {
	if(variable_get("site_api_key") != ''){
		$siteapikey = variable_get("site_api_key");
	}
	else
	{
		$siteapikey = "No API Key yet";
	}
	$form['site_information']['site_api_key'] = array(
		'#type' => 'textfield',
		'#title' => t('Site API Key'),
		'#default_value' => $siteapikey,
	);
	if(variable_get("site_api_key") != '')
	{
	  $form['actions']['submit'] = array(
		'#type' => 'submit',
		'#value' => 'Update Configuration',
	  );
	}
	$form['store'] = array(
		'#type' => 'value',
		'#value' => $siteapikey
	);
	$form['#submit'][] = 'my_submit_function';
}	
function my_submit_function($form, &$form_state) {
	if($form_state["values"]["site_api_key"] != $form_state["values"]["store"] && isset($form_state["values"]["site_api_key"])){
		 drupal_set_message('The API Key value has been changed');
	}
}